services:
  events_database:
    build: ./Servers/Collectors/Events
    volumes:
      - type: bind
        source: ./Servers/Collectors/Events/Data
        target: /Data
    
    networks:
      - main_network
    
    ports:
      - "127.0.0.1:5000:5000"

networks:
  main_network:
    driver: bridge

